# Generated by Django 4.1 on 2022-08-15 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_user_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=10)),
                ("estado", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=255)),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.IntegerField()),
                ("complemento", models.TextField(null=True)),
                ("bairro", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Casa", "Casa"), ("Trabalho", "Trabalho")],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
