# Generated by Django 4.1 on 2022-08-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0002_pedido_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto", name="descricao", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
